// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQf1iyTN08_OwbaWXpu8xvUJqvaTKI9QY',
    appId: '1:35632731479:web:ce45b5894016e4bcbc1a12',
    messagingSenderId: '35632731479',
    projectId: 'fir-login-448b3',
    authDomain: 'fir-login-448b3.firebaseapp.com',
    storageBucket: 'fir-login-448b3.appspot.com',
    measurementId: 'G-4D98V2S21N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJKvJosSKHv-oB-mEaDHcbfSHRBh8RQUQ',
    appId: '1:35632731479:android:cfab7e7810d0fab8bc1a12',
    messagingSenderId: '35632731479',
    projectId: 'fir-login-448b3',
    storageBucket: 'fir-login-448b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmepKYpZrVSkHOTYGyjx5nMHz1x54KP8M',
    appId: '1:35632731479:ios:4e9f38af869c1587bc1a12',
    messagingSenderId: '35632731479',
    projectId: 'fir-login-448b3',
    storageBucket: 'fir-login-448b3.appspot.com',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmepKYpZrVSkHOTYGyjx5nMHz1x54KP8M',
    appId: '1:35632731479:ios:a9e3a8fc009009e3bc1a12',
    messagingSenderId: '35632731479',
    projectId: 'fir-login-448b3',
    storageBucket: 'fir-login-448b3.appspot.com',
    iosBundleId: 'com.example.firebasetask.RunnerTests',
  );
}
